name: C/C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
    steps:
    - uses: actions/checkout@v3
    - name: check_gpu
      run: sudo lspci | grep -i NVIDIA
