name: C/C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: install driver
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install ubuntu-drivers-common
        sudo add-apt-repository ppa:graphics-drivers/ppa
        sudo apt update
        sudo apt upgrade
        ubuntu-drivers devices
        sudo ubuntu-drivers autoinstall
    - uses: Jimver/cuda-toolkit@v0.2.5
      id: cuda-toolkit
      with:
        cuda: '11.5.1'
    - name: vers
      run: nvcc -V
    - name: make
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux
    - name: make
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: make -f makeWindows
    - name: make test
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux run_test
    - name: make test
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: make -f makeWindows run_test 
